// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: binibft.proto

package binibft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BiniBFTOptions contains configuration for BiniBFT consensus
type BiniBFTOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request batching configuration
	RequestBatchMaxCount    uint64 `protobuf:"varint,1,opt,name=request_batch_max_count,json=requestBatchMaxCount,proto3" json:"request_batch_max_count,omitempty"`
	RequestBatchMaxBytes    uint64 `protobuf:"varint,2,opt,name=request_batch_max_bytes,json=requestBatchMaxBytes,proto3" json:"request_batch_max_bytes,omitempty"`
	RequestBatchMaxInterval string `protobuf:"bytes,3,opt,name=request_batch_max_interval,json=requestBatchMaxInterval,proto3" json:"request_batch_max_interval,omitempty"`
	// Message buffer and pool configuration
	IncomingMessageBufferSize uint64 `protobuf:"varint,4,opt,name=incoming_message_buffer_size,json=incomingMessageBufferSize,proto3" json:"incoming_message_buffer_size,omitempty"`
	RequestPoolSize           uint64 `protobuf:"varint,5,opt,name=request_pool_size,json=requestPoolSize,proto3" json:"request_pool_size,omitempty"`
	// Timeout configurations
	RequestForwardTimeout    string `protobuf:"bytes,6,opt,name=request_forward_timeout,json=requestForwardTimeout,proto3" json:"request_forward_timeout,omitempty"`
	RequestComplainTimeout   string `protobuf:"bytes,7,opt,name=request_complain_timeout,json=requestComplainTimeout,proto3" json:"request_complain_timeout,omitempty"`
	RequestAutoRemoveTimeout string `protobuf:"bytes,8,opt,name=request_auto_remove_timeout,json=requestAutoRemoveTimeout,proto3" json:"request_auto_remove_timeout,omitempty"`
	ViewChangeResendInterval string `protobuf:"bytes,9,opt,name=view_change_resend_interval,json=viewChangeResendInterval,proto3" json:"view_change_resend_interval,omitempty"`
	ViewChangeTimeout        string `protobuf:"bytes,10,opt,name=view_change_timeout,json=viewChangeTimeout,proto3" json:"view_change_timeout,omitempty"`
	LeaderHeartbeatTimeout   string `protobuf:"bytes,11,opt,name=leader_heartbeat_timeout,json=leaderHeartbeatTimeout,proto3" json:"leader_heartbeat_timeout,omitempty"`
	LeaderHeartbeatCount     uint64 `protobuf:"varint,12,opt,name=leader_heartbeat_count,json=leaderHeartbeatCount,proto3" json:"leader_heartbeat_count,omitempty"`
	CollectTimeout           string `protobuf:"bytes,13,opt,name=collect_timeout,json=collectTimeout,proto3" json:"collect_timeout,omitempty"`
	RequestPoolSubmitTimeout string `protobuf:"bytes,14,opt,name=request_pool_submit_timeout,json=requestPoolSubmitTimeout,proto3" json:"request_pool_submit_timeout,omitempty"`
	// BiniBFT specific configurations
	SyncOnStart        bool   `protobuf:"varint,15,opt,name=sync_on_start,json=syncOnStart,proto3" json:"sync_on_start,omitempty"`
	SpeedUpViewChange  bool   `protobuf:"varint,16,opt,name=speed_up_view_change,json=speedUpViewChange,proto3" json:"speed_up_view_change,omitempty"`
	LeaderRotation     bool   `protobuf:"varint,17,opt,name=leader_rotation,json=leaderRotation,proto3" json:"leader_rotation,omitempty"`
	DecisionsPerLeader uint64 `protobuf:"varint,18,opt,name=decisions_per_leader,json=decisionsPerLeader,proto3" json:"decisions_per_leader,omitempty"`
	RequestMaxBytes    uint64 `protobuf:"varint,19,opt,name=request_max_bytes,json=requestMaxBytes,proto3" json:"request_max_bytes,omitempty"`
	// Hierarchical sharding configuration
	ShardMajorityThreshold float64 `protobuf:"fixed64,20,opt,name=shard_majority_threshold,json=shardMajorityThreshold,proto3" json:"shard_majority_threshold,omitempty"`
	CrossShardThreshold    float64 `protobuf:"fixed64,21,opt,name=cross_shard_threshold,json=crossShardThreshold,proto3" json:"cross_shard_threshold,omitempty"`
	BatchSize              uint64  `protobuf:"varint,22,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	MaxBatchDelay          string  `protobuf:"bytes,23,opt,name=max_batch_delay,json=maxBatchDelay,proto3" json:"max_batch_delay,omitempty"`
	// Shard configuration
	Shards         []*ShardConfig `protobuf:"bytes,24,rep,name=shards,proto3" json:"shards,omitempty"`
	PrimaryLeader  uint64         `protobuf:"varint,25,opt,name=primary_leader,json=primaryLeader,proto3" json:"primary_leader,omitempty"`
	MaxFaultyNodes uint64         `protobuf:"varint,26,opt,name=max_faulty_nodes,json=maxFaultyNodes,proto3" json:"max_faulty_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BiniBFTOptions) Reset() {
	*x = BiniBFTOptions{}
	mi := &file_binibft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BiniBFTOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiniBFTOptions) ProtoMessage() {}

func (x *BiniBFTOptions) ProtoReflect() protoreflect.Message {
	mi := &file_binibft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiniBFTOptions.ProtoReflect.Descriptor instead.
func (*BiniBFTOptions) Descriptor() ([]byte, []int) {
	return file_binibft_proto_rawDescGZIP(), []int{0}
}

func (x *BiniBFTOptions) GetRequestBatchMaxCount() uint64 {
	if x != nil {
		return x.RequestBatchMaxCount
	}
	return 0
}

func (x *BiniBFTOptions) GetRequestBatchMaxBytes() uint64 {
	if x != nil {
		return x.RequestBatchMaxBytes
	}
	return 0
}

func (x *BiniBFTOptions) GetRequestBatchMaxInterval() string {
	if x != nil {
		return x.RequestBatchMaxInterval
	}
	return ""
}

func (x *BiniBFTOptions) GetIncomingMessageBufferSize() uint64 {
	if x != nil {
		return x.IncomingMessageBufferSize
	}
	return 0
}

func (x *BiniBFTOptions) GetRequestPoolSize() uint64 {
	if x != nil {
		return x.RequestPoolSize
	}
	return 0
}

func (x *BiniBFTOptions) GetRequestForwardTimeout() string {
	if x != nil {
		return x.RequestForwardTimeout
	}
	return ""
}

func (x *BiniBFTOptions) GetRequestComplainTimeout() string {
	if x != nil {
		return x.RequestComplainTimeout
	}
	return ""
}

func (x *BiniBFTOptions) GetRequestAutoRemoveTimeout() string {
	if x != nil {
		return x.RequestAutoRemoveTimeout
	}
	return ""
}

func (x *BiniBFTOptions) GetViewChangeResendInterval() string {
	if x != nil {
		return x.ViewChangeResendInterval
	}
	return ""
}

func (x *BiniBFTOptions) GetViewChangeTimeout() string {
	if x != nil {
		return x.ViewChangeTimeout
	}
	return ""
}

func (x *BiniBFTOptions) GetLeaderHeartbeatTimeout() string {
	if x != nil {
		return x.LeaderHeartbeatTimeout
	}
	return ""
}

func (x *BiniBFTOptions) GetLeaderHeartbeatCount() uint64 {
	if x != nil {
		return x.LeaderHeartbeatCount
	}
	return 0
}

func (x *BiniBFTOptions) GetCollectTimeout() string {
	if x != nil {
		return x.CollectTimeout
	}
	return ""
}

func (x *BiniBFTOptions) GetRequestPoolSubmitTimeout() string {
	if x != nil {
		return x.RequestPoolSubmitTimeout
	}
	return ""
}

func (x *BiniBFTOptions) GetSyncOnStart() bool {
	if x != nil {
		return x.SyncOnStart
	}
	return false
}

func (x *BiniBFTOptions) GetSpeedUpViewChange() bool {
	if x != nil {
		return x.SpeedUpViewChange
	}
	return false
}

func (x *BiniBFTOptions) GetLeaderRotation() bool {
	if x != nil {
		return x.LeaderRotation
	}
	return false
}

func (x *BiniBFTOptions) GetDecisionsPerLeader() uint64 {
	if x != nil {
		return x.DecisionsPerLeader
	}
	return 0
}

func (x *BiniBFTOptions) GetRequestMaxBytes() uint64 {
	if x != nil {
		return x.RequestMaxBytes
	}
	return 0
}

func (x *BiniBFTOptions) GetShardMajorityThreshold() float64 {
	if x != nil {
		return x.ShardMajorityThreshold
	}
	return 0
}

func (x *BiniBFTOptions) GetCrossShardThreshold() float64 {
	if x != nil {
		return x.CrossShardThreshold
	}
	return 0
}

func (x *BiniBFTOptions) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *BiniBFTOptions) GetMaxBatchDelay() string {
	if x != nil {
		return x.MaxBatchDelay
	}
	return ""
}

func (x *BiniBFTOptions) GetShards() []*ShardConfig {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *BiniBFTOptions) GetPrimaryLeader() uint64 {
	if x != nil {
		return x.PrimaryLeader
	}
	return 0
}

func (x *BiniBFTOptions) GetMaxFaultyNodes() uint64 {
	if x != nil {
		return x.MaxFaultyNodes
	}
	return 0
}

// ShardConfig defines configuration for a single shard
type ShardConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint64                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Leader        uint64                 `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Followers     []uint64               `protobuf:"varint,3,rep,packed,name=followers,proto3" json:"followers,omitempty"`
	Nodes         []uint64               `protobuf:"varint,4,rep,packed,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardConfig) Reset() {
	*x = ShardConfig{}
	mi := &file_binibft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardConfig) ProtoMessage() {}

func (x *ShardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_binibft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardConfig.ProtoReflect.Descriptor instead.
func (*ShardConfig) Descriptor() ([]byte, []int) {
	return file_binibft_proto_rawDescGZIP(), []int{1}
}

func (x *ShardConfig) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardConfig) GetLeader() uint64 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *ShardConfig) GetFollowers() []uint64 {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *ShardConfig) GetNodes() []uint64 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_binibft_proto protoreflect.FileDescriptor

const file_binibft_proto_rawDesc = "" +
	"\n" +
	"\rbinibft.proto\x12\abinibft\"\xb0\n" +
	"\n" +
	"\x0eBiniBFTOptions\x125\n" +
	"\x17request_batch_max_count\x18\x01 \x01(\x04R\x14requestBatchMaxCount\x125\n" +
	"\x17request_batch_max_bytes\x18\x02 \x01(\x04R\x14requestBatchMaxBytes\x12;\n" +
	"\x1arequest_batch_max_interval\x18\x03 \x01(\tR\x17requestBatchMaxInterval\x12?\n" +
	"\x1cincoming_message_buffer_size\x18\x04 \x01(\x04R\x19incomingMessageBufferSize\x12*\n" +
	"\x11request_pool_size\x18\x05 \x01(\x04R\x0frequestPoolSize\x126\n" +
	"\x17request_forward_timeout\x18\x06 \x01(\tR\x15requestForwardTimeout\x128\n" +
	"\x18request_complain_timeout\x18\a \x01(\tR\x16requestComplainTimeout\x12=\n" +
	"\x1brequest_auto_remove_timeout\x18\b \x01(\tR\x18requestAutoRemoveTimeout\x12=\n" +
	"\x1bview_change_resend_interval\x18\t \x01(\tR\x18viewChangeResendInterval\x12.\n" +
	"\x13view_change_timeout\x18\n" +
	" \x01(\tR\x11viewChangeTimeout\x128\n" +
	"\x18leader_heartbeat_timeout\x18\v \x01(\tR\x16leaderHeartbeatTimeout\x124\n" +
	"\x16leader_heartbeat_count\x18\f \x01(\x04R\x14leaderHeartbeatCount\x12'\n" +
	"\x0fcollect_timeout\x18\r \x01(\tR\x0ecollectTimeout\x12=\n" +
	"\x1brequest_pool_submit_timeout\x18\x0e \x01(\tR\x18requestPoolSubmitTimeout\x12\"\n" +
	"\rsync_on_start\x18\x0f \x01(\bR\vsyncOnStart\x12/\n" +
	"\x14speed_up_view_change\x18\x10 \x01(\bR\x11speedUpViewChange\x12'\n" +
	"\x0fleader_rotation\x18\x11 \x01(\bR\x0eleaderRotation\x120\n" +
	"\x14decisions_per_leader\x18\x12 \x01(\x04R\x12decisionsPerLeader\x12*\n" +
	"\x11request_max_bytes\x18\x13 \x01(\x04R\x0frequestMaxBytes\x128\n" +
	"\x18shard_majority_threshold\x18\x14 \x01(\x01R\x16shardMajorityThreshold\x122\n" +
	"\x15cross_shard_threshold\x18\x15 \x01(\x01R\x13crossShardThreshold\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x16 \x01(\x04R\tbatchSize\x12&\n" +
	"\x0fmax_batch_delay\x18\x17 \x01(\tR\rmaxBatchDelay\x12,\n" +
	"\x06shards\x18\x18 \x03(\v2\x14.binibft.ShardConfigR\x06shards\x12%\n" +
	"\x0eprimary_leader\x18\x19 \x01(\x04R\rprimaryLeader\x12(\n" +
	"\x10max_faulty_nodes\x18\x1a \x01(\x04R\x0emaxFaultyNodes\"t\n" +
	"\vShardConfig\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\x04R\x06leader\x12\x1c\n" +
	"\tfollowers\x18\x03 \x03(\x04R\tfollowers\x12\x14\n" +
	"\x05nodes\x18\x04 \x03(\x04R\x05nodesB9Z7github.com/hyperledger/fabric/orderer/consensus/binibftb\x06proto3"

var (
	file_binibft_proto_rawDescOnce sync.Once
	file_binibft_proto_rawDescData []byte
)

func file_binibft_proto_rawDescGZIP() []byte {
	file_binibft_proto_rawDescOnce.Do(func() {
		file_binibft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_binibft_proto_rawDesc), len(file_binibft_proto_rawDesc)))
	})
	return file_binibft_proto_rawDescData
}

var file_binibft_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_binibft_proto_goTypes = []any{
	(*BiniBFTOptions)(nil), // 0: binibft.BiniBFTOptions
	(*ShardConfig)(nil),    // 1: binibft.ShardConfig
}
var file_binibft_proto_depIdxs = []int32{
	1, // 0: binibft.BiniBFTOptions.shards:type_name -> binibft.ShardConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_binibft_proto_init() }
func file_binibft_proto_init() {
	if File_binibft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_binibft_proto_rawDesc), len(file_binibft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_binibft_proto_goTypes,
		DependencyIndexes: file_binibft_proto_depIdxs,
		MessageInfos:      file_binibft_proto_msgTypes,
	}.Build()
	File_binibft_proto = out.File
	file_binibft_proto_goTypes = nil
	file_binibft_proto_depIdxs = nil
}
