// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: consensus/protos/messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewMetadata struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ViewId                    uint64                 `protobuf:"varint,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	LatestSequence            uint64                 `protobuf:"varint,2,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	DecisionsInView           uint64                 `protobuf:"varint,3,opt,name=decisions_in_view,json=decisionsInView,proto3" json:"decisions_in_view,omitempty"`
	BlackList                 []uint64               `protobuf:"varint,4,rep,packed,name=black_list,json=blackList,proto3" json:"black_list,omitempty"`
	PrevCommitSignatureDigest []byte                 `protobuf:"bytes,5,opt,name=prev_commit_signature_digest,json=prevCommitSignatureDigest,proto3" json:"prev_commit_signature_digest,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ViewMetadata) Reset() {
	*x = ViewMetadata{}
	mi := &file_consensus_protos_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMetadata) ProtoMessage() {}

func (x *ViewMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_protos_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMetadata.ProtoReflect.Descriptor instead.
func (*ViewMetadata) Descriptor() ([]byte, []int) {
	return file_consensus_protos_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ViewMetadata) GetViewId() uint64 {
	if x != nil {
		return x.ViewId
	}
	return 0
}

func (x *ViewMetadata) GetLatestSequence() uint64 {
	if x != nil {
		return x.LatestSequence
	}
	return 0
}

func (x *ViewMetadata) GetDecisionsInView() uint64 {
	if x != nil {
		return x.DecisionsInView
	}
	return 0
}

func (x *ViewMetadata) GetBlackList() []uint64 {
	if x != nil {
		return x.BlackList
	}
	return nil
}

func (x *ViewMetadata) GetPrevCommitSignatureDigest() []byte {
	if x != nil {
		return x.PrevCommitSignatureDigest
	}
	return nil
}

var File_consensus_protos_messages_proto protoreflect.FileDescriptor

const file_consensus_protos_messages_proto_rawDesc = "" +
	"\n" +
	"\x1fconsensus/protos/messages.proto\x12\rbinibftprotos\"\xdc\x01\n" +
	"\fViewMetadata\x12\x17\n" +
	"\aview_id\x18\x01 \x01(\x04R\x06viewId\x12'\n" +
	"\x0flatest_sequence\x18\x02 \x01(\x04R\x0elatestSequence\x12*\n" +
	"\x11decisions_in_view\x18\x03 \x01(\x04R\x0fdecisionsInView\x12\x1d\n" +
	"\n" +
	"black_list\x18\x04 \x03(\x04R\tblackList\x12?\n" +
	"\x1cprev_commit_signature_digest\x18\x05 \x01(\fR\x19prevCommitSignatureDigestB\x1eZ\x1cbinibft-poc/consensus/protosb\x06proto3"

var (
	file_consensus_protos_messages_proto_rawDescOnce sync.Once
	file_consensus_protos_messages_proto_rawDescData []byte
)

func file_consensus_protos_messages_proto_rawDescGZIP() []byte {
	file_consensus_protos_messages_proto_rawDescOnce.Do(func() {
		file_consensus_protos_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_protos_messages_proto_rawDesc), len(file_consensus_protos_messages_proto_rawDesc)))
	})
	return file_consensus_protos_messages_proto_rawDescData
}

var file_consensus_protos_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_consensus_protos_messages_proto_goTypes = []any{
	(*ViewMetadata)(nil), // 0: binibftprotos.ViewMetadata
}
var file_consensus_protos_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consensus_protos_messages_proto_init() }
func file_consensus_protos_messages_proto_init() {
	if File_consensus_protos_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_protos_messages_proto_rawDesc), len(file_consensus_protos_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_protos_messages_proto_goTypes,
		DependencyIndexes: file_consensus_protos_messages_proto_depIdxs,
		MessageInfos:      file_consensus_protos_messages_proto_msgTypes,
	}.Build()
	File_consensus_protos_messages_proto = out.File
	file_consensus_protos_messages_proto_goTypes = nil
	file_consensus_protos_messages_proto_depIdxs = nil
}
